### ISSUE TITLE
CanFlood Install Error

### ISSUE THREAD

**Issue by jdngibson** [NRCan/CanFlood#27]
Getting the following error when installing CanFlood 1.1.0 plugin:
![CanFlood Install Error](https://user-images.githubusercontent.com/64096979/146790297-bed3de0b-e78b-46f9-912a-0f6dccca5420.JPG)

Using QGIS 3.16.14 Hanover.  Here is the 'About' info:
![QGIS About](https://user-images.githubusercontent.com/64096979/146790429-3c99656a-f428-425b-bb42-058bb2b287f2.JPG)

**Comment by cefect** [comment]
You've installed QGIS with the old dependencies (Qt=5.11.2 vs. 5.15 .2). This can happen if you install QGIS via the 'Long-term release in old OSGeo4W (continued with previous dependencies)' standalone exes rather than the new msis [here](https://qgis.org/en/site/forusers/download.html).
