### ISSUE TITLE
Fix committee subfolder

### ISSUE THREAD

**Issue by cefect** [NRCan/CanFlood#30]
links still point to old repository. need to move the data and fix the readme

https://github.com/IBIGroupCanWest/CanFlood/tree/master/committee

**Comment by cefect** [comment]
e.g. https://github.com/NRCan/CanFlood/tree/master/committee

**Comment by GrahamD-IBI** [comment]
@cefect Completed and created a pull request for this branch

**Comment by cefect** [comment]
https://github.com/NRCan/CanFlood/pull/81
