### ISSUE TITLE
Risk (L2): ValueError: x and y arrays must have at least 2 entries

### ISSUE THREAD

**Issue by TC-999** [NRCan/CanFlood#35]
Hi Seth,

As the last step in the case study, I came across this error with my own inventory data with the following log messages. Appreciate any help.
![image](https://user-images.githubusercontent.com/101820349/159803484-d3254562-90c7-4c90-9ceb-d0f8d76e0d9d.png)

**Comment by cefect** [comment]
Hi Tong,
Sorry to hear you're having issues with the L2 risk module. My first guess is you're trying to create a risk curve with too few events.  I suggest reading [this section](https://canflood.readthedocs.io/en/dev/05_toolsets.html#risk-l2) of the manual. How many hazard events are you using? 

If this still doesn't work, please provide all the info described [here](https://github.com/NRCan/CanFlood/issues/6) so we can investigate further.

**Comment by TC-999** [comment]
It was solved with multiple events. Thanks!
