### ISSUE TITLE
No Inventory Results

### ISSUE THREAD

**Issue by jvandevalk** [NRCan/CanFlood#36]
Hi, I'm getting the following critical errors when inputting my data: 

2022-04-12T13:22:46     WARNING    cf.BuildDialog.vlay_get_fdata: got no results! from 'finv_tuk_finv'
2022-04-12T13:22:46     CRITICAL    allow_none=FALSE and no results

Any ideas?

**Comment by cefect** [comment]
do you have some selection or AOI set? Seems like everything is being filtered out. 

What command are you trying that is causing the error?

**Comment by jvandevalk** [comment]
I did not have an AOI set. Those errors are from when I validated the inputs in the build toolset.

**Comment by cefect** [comment]
OK. What does your [compiled inventory](https://canflood.readthedocs.io/en/latest/toolsets.html#inventory) look like? 

I can take a closer look if you send me the [control file and model package ](https://canflood.readthedocs.io/en/latest/introduction.html#control-files). (the  previous link you shared only has the data inputs).

**Comment by jvandevalk** [comment]
I've put the files in the google drive - let me know if you need any others.

**Comment by cefect** [comment]
I assume you're trying to validate for L2? For this, you need to specify damage functions.:

> no value provided for 'risk_fps.dmgs'. optional=False
