### ISSUE TITLE
L2 complex failure polys. ValueError: 'x and y arrays'

### ISSUE THREAD

**Issue by blhumphreys** [NRCan/CanFlood#38]
I am trying to run an L2 risk model using my own data. I am able to build and fully validate the model using 7 hazard rasters and complex failure polygons, but when I go to run L2 risk I get one of the following errors, depending on whether I set event_rels to 'mutually exclusive' or 'independent':
- Mutually exclusive - 'x and y arrays must have at least 2 entries'
- Independent - 'attribution not implemented for event_rels='indep'' 

Could you please help us resolve these issues? It was mentioned in a previous post that the 'x and y arrays must have at least 2 entries' error can be resolved by not using enough hazard events, but that doesn't appear to be the issue here.

Thanks

![Error2](https://user-images.githubusercontent.com/100965696/166056735-cc0810f8-76f0-4b97-94f8-cecde6827c10.JPG)
![Error1](https://user-images.githubusercontent.com/100965696/166056741-981b8a84-1ce3-4f5d-9cde-74648388de3f.JPG)

**Comment by cefect** [comment]
Thank you for the question. 
For event_rels=indep, Try turning 'Generate attribution matrix' off (on the Setup tab). 
for mutex, what does your 'exlikes' file look like? (esp compared to your finv)

**Comment by blhumphreys** [comment]
Thanks for the reply.

For event_rels=indep, when I turn 'Generate attribution matrix' off I get the 'x and y arrays must have at least 2 entries' error instead.

Regarding the mutex error, could you please let me know what I should be looking for in the exlikes files? 

Also, I'm not sure if this is relevant but I only sampled 6 of my 7 hazard rasters in the Conditional P section of the build toolset, as one of them is a base run.

Thanks.

**Comment by cefect** [comment]
I'm wondering how many rows and columns there are and how many zeros there
are, and how this relates to the finv. It's probably easiest if you just
send the model package. This should be aspatial and you can remove any
non-CanFlood columns.
*Seth Bryant*

**Comment by blhumphreys** [comment]
Sounds good, I have just sent the zipped model package to you via the email on your GitHub page. Please let me know if you need any more info.

Thanks.

**Comment by cefect** [comment]
Thanks @blhumphreys. I reviewed your ModelPackage.zip  and noticed the following:

- you have some data files which are not referenced in the control file (there's nothing wrong with this.. .just something to note as it can be confusing when debugging).
- There are 7 events in your 'evals', 'dmgs', and 'expos', but only 6 in your exlikes. Try either removing the 'BaseWSEmax200yr_c - LOCAL' from all the data files, or adding it to the exlikes.

Let me know how it goes so I can improve the error messages.

**Comment by blhumphreys** [comment]
Thanks for the advice @cefect.

I removed 'BaseWSEmax200yr_c - LOCAL' from all of the data files, and am now getting this error: 'some complex event probabilities exceed 1'. Do you know what could be causing this?

Thanks.

![image](https://user-images.githubusercontent.com/100965696/167165087-f5f589b9-64e6-4e50-975b-e118b141bdae.png)

**Comment by cefect** [comment]
Hi @blhumphreys, glad to hear you've progressed onto the next error! 

this means the failure polygons you're providing are exceeding 100% (which violates the definition of probability). Check your exlikes for rows with big values, or try a different event_rels assumption. 

Cheers,

**Comment by cefect** [comment]
closing as you're now having a separate issue. please open another ticket with the new problem if you still need help.

**Comment by blhumphreys** [comment]
Thanks for the suggestions @cefect. Unfortunately I am still getting the same error, so have opened up a new issue (linked above).
