### ISSUE TITLE
5.2. Model tables are missing table numbers

### ISSUE THREAD

**Issue by cefect** [NRCan/CanFlood#43]
https://canflood.readthedocs.io/en/latest/toolsets.html#model

tables need a table number (e.g., table 1.1)

**Comment by dhanyatha-harish-ibigroup** [comment]
The link mentioned here doesnt seem to work, cause of the new builds. Navigated to model page under toolsets section ( https://canflood.readthedocs.io/en/latest/05_toolsets.html#model ) and there are 2 summary tables ( or sections ) which do not have numbers and the rest of the tables seem to have their table numbers and looks like they are all in order and increments of 5. Should we add a table number for these 2 summary tables? and if so, to maintain the continuity, should we change the table numbers in the rest of the document?

**Comment by cefect** [comment]
I trust you to come up with something consistent and professional looking. How do other RTD projects handle table references? In general, someone should go through and spend a few hours improving the readability of all the tables.

**Comment by dhanyatha-harish-ibigroup** [comment]
A good way to go about it is to add a page table indexes listing what each table refers to and having each of these linked to the tables in their respective pages which is to say that we could create an index page just for tables.

**Comment by GrahamD-IBI** [comment]
No problem, I can update the tables across the document for consistency.

**Comment by GrahamD-IBI** [comment]
@cefect Completed and created a pull request for this branch
