### ISSUE TITLE
maximum supported events

### ISSUE THREAD

**Issue by cefect** [NRCan/CanFlood#47]
In addition to this, we will need to run 6 breach scenarios for 3 different events (total of 18 rasters) for our analysis. Is there a way to run all 18 rasters together? It seems that the tool is either limited to 8 (max inputs for the Conditional P tab), or until the total for each row in the exlikes row is greater than 1.

Please let me know if you'd like me to post this as a new issue.

_Originally posted by @blhumphreys in https://github.com/NRCan/CanFlood/issues/46#issuecomment-1121456651_

**Comment by cefect** [comment]
You are correct, the GUI only supports 8 events. The model however does not have this limitation. So you could pretty easily construct the data files with all the events you want using a combination of the GUI and excel... and you should be able to run as many events as you like (within the limits you mention).

**Comment by blhumphreys** [comment]
Good to know, thanks.

Do you have a suggestion for how to do an analysis that considers all 18 of our scenarios? The total for most rows in the exlikes file will be greater than 1.

**Comment by cefect** [comment]
you could assume the events are independent.

exlikes stores the probabilities of a set of conditional events (which can be either mutually exclusive or independent).  The definition of a probability space has to be less than one. See [figure 3-5](https://canflood.readthedocs.io/en/latest/applications_and_workflows.html#event-relations) for how this is calculated.  

note that CanFlood only supports a fairly simplistic assessment of defense failure

**Comment by blhumphreys** [comment]
Hi @cefect, I have combined the model files as suggested, and have now successfully run the risk L2 model without the res_per_asset box being checked. When I check the box, however, I get the following error: 'got negative extrapolation on '2002044': -912.55'.

Do you know what this is referring to? I have checked asset 2002044 in the model files and don't see anything out of the ordinary.
