### ISSUE TITLE
getting error "impact values decreasing"

### ISSUE THREAD

**Issue by CarolLWagner** [NRCan/CanFlood#48]
I am getting the error "impact values decreasing." I am trying to run L2 analysis of buildings for which I have f0_elv = height of first floor above ground level (m), f0_scale= floor area (m2), f0_cap = assessment value ($), 4 water surface level events with different return periods, and a DEM file. The values in the expos*.csv file are correct; the values is gels*.csv file look correct as the ground elevation height at each point. I am using a damage curve file with expos_var as water height above floor, impact_var as building repair and restoration cost, and scale_var as floor area. The inventory felv is set to "ground." I have tried changing the f0_cap values to zero but still get the error message. Is there something amiss with my data assignments and/or logic of what should be happening? 

My QGIS is 3.16.14, CanFlood is 1.1.0 Attached are 2 screenshots of the error and the debug log file.

![Error_impact_values_decreasing](https://user-images.githubusercontent.com/61026203/168172991-93d12689-0bf1-4125-8ce1-124f13f882f5.JPG)
![Error_2_impact_values_decreasing](https://user-images.githubusercontent.com/61026203/168173025-d3a9def2-db88-4b0b-bd59-c5349d30acda.JPG)
[qgis_debug.log](https://github.com/NRCan/CanFlood/files/8682760/qgis_debug.log)

**Comment by cefect** [comment]
Thank you for the question. 
This error is communicating that the intersection of your hazard rasters and your inventory is yielding some non-monotonic values. in other words, your bigger floods are not returning bigger values. This can happen if there are some errors between  your hazard layers. 

If you look at the [QGIS DEBUG logger](https://stackoverflow.com/a/61669864/9871683
) it may tell you exactly which assets this is happening for.  Regardless, your expos file should help identify the offending assets. Often, simply shifting an asset by a few meters is sufficient to resolve the issue. In egregious cases, you may have to correct the hazard layer or the expos file manually.
