### ISSUE TITLE
add damage function library purge

### ISSUE THREAD

**Issue by cefect** [NRCan/CanFlood#54]
Often, a user will have a damage function library with many 'extra' curves not referenced in the model. It would be nice to provide a simple tool on the Build - Inventory tab to remove any damage functions from the xls not found in the finv.

**Comment by cefect** [comment]
Proposed tool would first scan the inventory referenced in the control file to identify the list of unique curve tags. These tags would then be pulled from the selected curve library xls and copied to a new xls. 

This allows the user to quickly and transparently customize the curve library based on their inventory. The pdf reporter would then only show the referenced curves.

Proposed button location:

![image](https://user-images.githubusercontent.com/47092034/175366741-70e14720-0d8e-4eaa-824e-89c2c1151c7f.png)

**Comment by jvandevalk** [comment]
That seems like a good solution to me! That way the report will only have the curves used in the model, and that's what I'm after.

**Comment by cefect** [comment]
Hi @jvandevalk, 
check out the new tool here:
https://youtu.be/2abgdFdY1c8

Here's my proposed tooltip for the button:

**Comment by jvandevalk** [comment]
Looks brilliant! Thanks Seth, and great video.
