### ISSUE TITLE
Building class information for the IBI 2020 curve?

### ISSUE THREAD

**Issue by ywang579** [NRCan/CanFlood#73]
Hello,

We are trying to use the IBI 2020 curve for a project in BC. However, we do not know how to assign building categories (fX_tag) to our building data.

In the IBI 2020 curve, the building categories are listed as mfSlab150, mfSlab151, etc. We cannot find adequate information in the CanFlood documentation to determine which buildings these codes stand for. We also check the Flood Risk Assessment for BC’s Lower Mainland report (IBI 2020) and its Appendix A, but still did not find enough information.

Is it possible to add the relevant information somewhere in the CanFlood documentation if it is not already there? Thank you!
![image](https://user-images.githubusercontent.com/125609800/219495123-8f6de918-0f2f-4e47-b64a-5abce5dec444.png)

**Comment by obwb** [comment]
Thank you for your enquiry.  I am passing on your note to the technical lead for the project, David Sol.

Regards,

Dr. Nelson R. Jatel, P.Ag.
Water Stewardship Director | Okanagan Basin Water Board
obwb.ca<http://www.obwb.ca/> | (c.) 250.308.9449 | (o.) 250 469.6295

***@***.***<https://www.linkedin.com/in/nelsonjatel/>


From: Yinlue Wang ***@***.***>
Sent: February 16, 2023 1:53 PM
To: NRCan/CanFlood ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [NRCan/CanFlood] Building class information for the IBI 2020 curve? (Issue #73)

CAUTION: This message was sent from outside the organization. Please do not click links, open attachments, or respond unless you recognize the source of this email and know the content is safe.



Hello,

We are trying to use the IBI 2020 curve for a project in BC. However, we do not know how to assign building categories (fX_tag) to our building data.

In the IBI 2020 curve, the building categories are listed as mfSlab150, mfSlab151, etc. We cannot find adequate information in the CanFlood documentation to determine which buildings these codes stand for. We also check the Flood Risk Assessment for BC’s Lower Mainland report (IBI 2020) and its Appendix A, but still did not find enough information.

Is it possible to add the relevant information somewhere in the CanFlood documentation if it is not already there? Thank you!
[image]<https://user-images.githubusercontent.com/125609800/219495123-8f6de918-0f2f-4e47-b64a-5abce5dec444.png>

**Comment by cefect** [comment]
Thank you for the question. CanFlood is a modelling platform that provides a library of vulnerability functions from various sources for convenience. Documentation for these functions is outside the scope of CanFlood. You would need to contact the authors of whatever curves you're interested in if the provided reports do not contain enough information.

I happen to have worked on the project in question, so I can point you towards the FBC report you mention, Appendix A 'Vulnerability Functions for Buildings and Facilities in BC’s Lower Mainland',  Annex A – 'Building Repair Asset Table'. If you are still unable to find what you're looking for, I suggest contacting FBC. 

Sorry I can't be more helpful,
