### ISSUE TITLE
fX_tag got nulls | IBI 2020 Curves | FBC Dataset

### ISSUE THREAD

**Issue by akhilk15** [NRCan/CanFlood#89]
Hi, I am working with IBI 2020 curves and FBC CanFlood building datasets. The asset inventory dataset has "null" values assigned to some of the assets (in f2_tag, f3_tag, f4_tag). I guess the intention was to tell CanFlood that no curve has been assigned to these assets. I am not doing any edits to the dataset, but when I run the CanFlood model, I am getting a python error that says "f2_tag got nulls...see logger". Can you please guide me on how to fix it? Thanks!
![image](https://user-images.githubusercontent.com/17062653/235982950-08a2ffbc-ed8d-4374-863c-b4575b880af6.png)

**Comment by akhilk15** [comment]
Please see the asset inventory dataset screenshot. You can see _NULL_ value assigned to some of the assets in fX_tag category.
![image](https://user-images.githubusercontent.com/17062653/236010321-5c8b7d4b-17c0-410e-8aff-433c0cf8ffb8.png)

**Comment by cefect** [comment]
Thank you for the question. Did you try assigning an arbitrary curve to these, then set fx_scale to zero?


Let me know if this works for you,

**Comment by akhilk15** [comment]
Hi @cefect , thank you for your help. This trick works. But now there is another issue. Because I can only select one depth-damage curve at a time from the library, Python is giving an error that it could not load other requested dfuncs. As you can see in the asset inventory screenshot above, multiple curves have been referenced. Is there a way I can select load multiple dfuncs at the same time?

**Comment by cefect** [comment]
are all of the curves you've specified in the inventory included in the curves.xls file?

**Comment by akhilk15** [comment]
actually, the IBI2020 curves are split into different categories, as you can see in the screenshot below. I can only select only one Excel sheet at a time. There is no single Excel sheet that has all the curves. It seems like I will have to run the analysis for each curve one by one. Any suggestions please?
![image](https://user-images.githubusercontent.com/17062653/236300487-11e826e0-39c7-4b48-9c59-bb575dcd8e46.png)

**Comment by cefect** [comment]
The vFunc library tool is for quickly building models. If you want to mix curves from different libraries, you'll have to merge all the tabs into one spreadsheet. This is easy to do in Excel (right click tab > move or copy...). There was some discussion on including a merge feature like this into CanFlood, but such a feature has not been implemented.

**Comment by akhilk15** [comment]
Thank you, @cefect. I was able to create one compiled spreadsheet and it worked. I may have some other questions later on. But I think I am good for now. Our group will be using this tool more extensively moving on. If you like, I can share more about our learnings and the need for any feature updates necessary to further advance this tool. Thanks!  Akhil Kumar, P.Eng., City of Vancouver.
