### ISSUE TITLE
Missing Depth-Damage Curves in IBI 2020 Dataset

### ISSUE THREAD

**Issue by akhilk15** [NRCan/CanFlood#93]
Hi Seth @cefect, this is not an issue but letting you know that we recently discovered that the IBI 2020 NRP contents damage curves are missing two curves in the Excel sheets - warehouse (fX_tag "01Warehouse.inStk.comp") and office ( fX_tag "02Office.inStk.comp") spaces. After a deep investigation of IBI 2020 deliverables, we found that these two curves were actually composite curves computed as:

- 01Warehouse.inStk.comp - mean of 5 root naics: ['11Ag', '31Manu', '32Manu2', '41Whole', '48Transpo']
- 02Office.inStk.comp - mean of 5 root naics: ['51Misc', '52Fi', '54Tech', '56Admin', '61Edu']

I found this information from the "duplicate.log" file, which I guess was the main script written to batch-run CanFlood scenarios. This information is not written elsewhere in any documentation. I understand these were developed mainly for the FBC's LMFRA study, but users of this dataset (like us - City of Vancouver) will find issues if the depth-damage curves are not updated in CanFlood's source repository. There are many NRP assets which are tagged with these two curves. I would suggest updating the IBI 2020 curves to resolve this issue. I have attached the new Excel sheet below. Kindly have a look. Thanks!

[DmgFuncs_NRPcont_20200517_inStk - with composites.xls](https://github.com/NRCan/CanFlood/files/14174485/DmgFuncs_NRPcont_20200517_inStk.-.with.composites.xls)

Regards,
Akhil

**Comment by cefect** [comment]
Hi Akhil, this makes sense. I'm not sure why these two curves were not included in the CanFlood curve library originally... I assume they were included in a later deliverable to FBC and the CanFlood set was never updated. In general, I suggest using the model files from FBC as these should all work together... not the CanFlood libraries (even though they should be the same). 

Regardless, I've updated the library with your file ( 441066b…35abad8). You can see this on the dev branch now, but I'm not sure when this will be tested and pushed out to the main branch.
